# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TPDelegateMatrioskaDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TPDelegateMatrioskaDemo

  pod 'TPDelegateMatrioska', :path => '../'

  target 'TPDelegateMatrioskaDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TPDelegateMatrioskaDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
